/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Address {
  abbr?: boolean;
  type: 'city' | 'state' | 'country' | 'streetName' | 'streetAddress' | 'countryCode' | 'zipCode';
}
