/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Date {
  abbr?: boolean;
  dateLocale?: string;
  end?: string;
  start?: string;
  type: 'weekday' | 'future' | 'between' | 'past' | 'month';
}
