/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Git {
  type: 'branch' | 'commitEntry' | 'commitMessage' | 'commitSha' | 'shortSha';
}
