/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ID {
  randomInteger?: {
    max: number;
    min: number;
  };
  sequentialInteger?: {
    start: number;
  };
  uuid?: string;
}
