/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Person {
  gender?: 'M' | 'F';
  type: 'firstName' | 'lastName' | 'middleName' | 'jobTitle' | 'prefix' | 'suffix' | 'title' | 'jobDescriptor' | 'jobArea' | 'jobType';
}
