/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Vehicle {
  type: 'vehicle' | 'color' | 'manufacturer' | 'model' | 'type' | 'vin' | 'fuel';
}
