/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { ID, Address, Date, Enum, Git, Person, Random, Vehicle } from '.';

export interface Zap {
  tables: {
    fields: {
      category: {
        ID?: ID;
        address?: Address;
        date?: Date;
        enum?: Enum;
        git?: Git;
        person?: Person;
        random?: Random;
        vehicle?: Vehicle;
      };
      name: string;
    }[];
    name: string;
    quantity: number;
  }[];
}
